### ISSUE TITLE
Misskey v12.103.1 API changes

### ISSUE THREAD

**Issue by ghost** [h3poteto/megalodon#1106]
There's been a change to an endpoint in Misskey API: https://github.com/misskey-dev/misskey/issues/8243#issuecomment-1027507263 for `drive/files/create`
An update may be necessary to make the file upload function work on instances running the newer version.

**Comment by gaycookie** [comment]
I would assume that this is the reason why I keep receiving this error.
I've tried everything I know but I'm so damn sure that I'm providing a file 😂

```
{
  error: {
    message: 'File required.',
    code: 'FILE_REQUIRED',
    id: '4267801e-70d1-416a-b011-4ee502885d8b',
    kind: 'client'
  }
}
```

**Comment by ThatOneCalculator** [comment]
Should be closed due to https://github.com/h3poteto/megalodon/pull/1920

**Comment by h3poteto** [comment]
Yes.
