### ISSUE TITLE
missing "min_id" parameter in getAccountStatuses for Mastodon?

### ISSUE THREAD

**Issue by fasiha** [h3poteto/megalodon#1435]
I see in https://docs.joinmastodon.org/methods/accounts/ that for `/api/v1/accounts/:id/statuses`, the `min_id` parameter has been available since 2.6.0, and I can confirm that it does work on Mastodon. However, in https://github.com/h3poteto/megalodon/blob/4df974deee19dd9638b72712690c76e947e042a9/megalodon/src/mastodon.ts#L285-L292 it looks like this is missing? I see in https://github.com/h3poteto/megalodon/issues/1131 that there's some discussion about Misskey but I didn't find an issue/PR about this for Mastodon.

Would you be open to a PR to add this? I'll be happy to try making one. Thank you!

**Comment by h3poteto** [comment]
Oh, that's right, this should be available for Mastodon.
I'm waiting for your PR, thank you!
