### ISSUE TITLE
Handle Link header for next/prev following list for Mastodon

### ISSUE THREAD

**Issue by fasiha** [h3poteto/megalodon#1444]
The documentation for Mastodn's [`api/v1/accounts/:id/following`](https://docs.joinmastodon.org/methods/accounts/) endpoint says

> Because the ID of follow relationships is not generally used or provided with any API calls, an HTTP Link header is used instead to indicate next and previous pages. You will have to parse this header yourself to extract the paging URLs.

And there's an example:
```
Link: <https://mastodon.social/api/v1/accounts/1/followers?limit=2&max_id=7628164>; rel="next", <https://mastodon.social/api/v1/accounts/1/followers?limit=2&since_id=7628165>; rel="prev"
```

So after I call Megalodon's `getAccountFollowing` function, I I can get the Response's `headers` and extract the `Link` header and parse it (there's this nice parser: https://www.npmjs.com/package/parse-link-header that works well), but if I make a request to the `next` URL, I'll have to do all the error handling myself, which is annoying.

Would you be interested in a PR that parses this `Link` header and fetches each `next` link to build a *full* list of follows?

Thanks!

**Comment by h3poteto** [comment]
Do you mean that you want to get *full list* of follows when you call `getAccountFollowing`?

**Comment by fasiha** [comment]
> Do you mean that you want to get _full list_ of follows when you call `getAccountFollowing`?

Yes 😁, instead of just the first page.

**Comment by fasiha** [comment]
Maybe that could be another method (since it might take a long time to iterate through all the pages)? Or can we make `getAccountFollowing` pagination-aware?

**Comment by h3poteto** [comment]
> since it might take a long time to iterate through all the pages

Yes, I'm worried about it too. So you should make another method.

**Comment by fasiha** [comment]
Thank you!!! Excited to use this in production once you publish a new version to nom 💜! 🙇
