### ISSUE TITLE
Function `generateAuthUrl` is not a part of `MegalodonInterface`

### ISSUE THREAD

**Issue by urmaul** [h3poteto/megalodon#1477]
Right now it looks like the way to generate auth URL is to register a new app. Or to assume the type on client. Both options don't seem right.

Is it possible to expose `generateAuthUrl` in `MegalodonInterface`?

**Comment by h3poteto** [comment]
`generateAuthUrl` is used for `registerApp`, why do you want to expose it as the interface?

**Comment by urmaul** [comment]
I'm building a matrix.org chatbot that forwards you toots from you subscriptions. It has to support multiple users per server. And I'd like to do it without spamming the server by creating a new application every time someone wants to log in.

**Comment by h3poteto** [comment]
> And I'd like to do it without spamming the server by creating a new application every time someone wants to log in.

Ah, I see. That makes sense.

**Comment by h3poteto** [comment]
I have one concern.
Misskey has a different interface
https://github.com/h3poteto/megalodon/blob/6bb44bfc14208ae4e7995194d59ea6fcbd050d60/megalodon/src/misskey.ts#L117
so I'm wondering what to do.

**Comment by MarkMcKinney** [comment]
@urmaul @h3poteto Hey both, was a better solution found? I'm facing a similar issue. Should I just register a new app every time a user wants to add a Mastodon account to my platform?
