### ISSUE TITLE
postStatus with scheduled_at not working for Mastodon

### ISSUE THREAD

**Issue by potproject** [h3poteto/megalodon#1577]
Sending a value that includes scheduled_at in postStatus results in `Promise<reject>`.

Error Message:
```
[TypeError: undefined is not an object (evaluating 's.emojis.map')]
```

https://github.com/h3poteto/megalodon/blob/master/megalodon/src/mastodon/api_client.ts#L609

Software: Mastodon
Software Version: 4.0.2
Megalodon Version: 5.1.1

I think ScheduledStatus is returned if scheduled_at is present, but it fails to take them into account.ScheduledStatus does not contain emojis, so it is an error.

https://docs.joinmastodon.org/methods/statuses/#create
>Returns: [Status](https://docs.joinmastodon.org/entities/Status/). When scheduled_at is present, [ScheduledStatus](https://docs.joinmastodon.org/entities/ScheduledStatus/) is returned instead.

**Edit:** If this error occurs, the post itself seems to be done

**Comment by h3poteto** [comment]
Ah, that makes sense.
