### ISSUE TITLE
getNotifications type : "achievementEarned" not worked for misskey v13

### ISSUE THREAD

**Issue by potproject** [h3poteto/megalodon#1591]
The misskey v13 implementation of the "achievementEarned" type returns the user as null, so when getNotifications is used, an error occurs in this code section.

```
null is not an object (evaluating 'u.username')
```

https://github.com/h3poteto/megalodon/blob/master/megalodon/src/misskey/api_client.ts#L53

API Response:
```json
[
{
    "id":"9bbz9taaoq",
    "createdAt":"2023-02-17T10:54:14.914Z",
    "type":"achievementEarned",
    "isRead":true,
    "userId":null,
    "user":null,
    "achievement":"login3"
},
...
]
```
![image](https://user-images.githubusercontent.com/6498055/219633439-6179edb8-d826-4df9-bfcb-c25ea638a4ef.png)

**Comment by h3poteto** [comment]
refs: https://github.com/h3poteto/megalodon/issues/1669
