### ISSUE TITLE
Missing Favorite ID from Misskey API Response

### ISSUE THREAD

**Issue by mogita** [h3poteto/megalodon#1653]
### The Problem

Misskey API endpoint `https://misskey.io/api/i/favorites` returns the list as its "Favorite" entity, meanwhile `megalodon` parses the response and turns them into the "Status" entity. The conceptual "Favorite ID" is missing after this process, making it impossible to properly set `max_id` (alias to Misskey's `untilId`) or `min_id` (alias to `sinceId`).

<details>
  <summary>Misskey's original response</summary>

Note the outermost "id" `9d2zeg8dbv` stands for the "favorite Id", which differs from the "nodeId" `9d1afixabh`:

```json
{
    "createdAt": "2023-04-02T13:07:20.365Z",
    "id": "9d2zeg8dbv",
    "note": {
        "createdAt": "2023-04-01T08:40:33.934Z",
        "cw": null,
        "fileIds": [],
        "files": [],
        "id": "9d1afixabh",
        "localOnly": false,
        "reactionEmojis": {
            "4b8f_kawaiii@misskey.gamelore.fun": "https://nos3.arkjp.net/emoji.webp?url=https%3A%2F%2Fsjc1.vultrobjects.com%2Fmisskey%2Ffiles%2F7c028a19-9b4d-4a99-aefc-3b4b4349d8cb.png"
        },
        "reactions": {
            ":4b8f_kawaiii@misskey.gamelore.fun:": 7,
            ":ara_kawaii@.:": 8,
            <redacted for simplicity>
        },
        "renoteCount": 71,
        "renoteId": null,
        "repliesCount": 0,
        "replyId": null,
        "text": "misskey.ioに新しい絵文字 :murakamisan_tutinoko_crawling: (`murakamisan_tutinoko_crawling`)が追加されたかも。\n$[x2 :murakamisan_tutinoko_crawling:]",
        "user": {
            "avatarBlurhash": "yBC7c]tS00Z$ElRjYk]yofAJWB%1niI.4Te.T{S$}rwJM}Q,WAPVS$+uxZM{MJaecZW=+txaENz:jZF2ba-obINH]#n$NLW=O?jZRQ",
            <redacted for simplicity>
        },
        "userId": "8rghsiwkp1",
        "visibility": "public"
    },
    "noteId": "9d1afixabh"
}
```
</details>

<details>
  <summary>Megalodon's wrapped response</summary>

Note the "id" field is actually "noteId" `9d1afixabh`, and the "favorite Id" `9d2zeg8dbv` has been lost:

```json
{
    "id": "9d1afixabh",
    "uri": "",
    "url": "",
    "account": {
        "id": "8rghsiwkp1",
        "username": "emoji_bot",
        <redacted for simplicity>
    },
    "in_reply_to_id": null,
    "in_reply_to_account_id": null,
    "reblog": null,
    "content": "misskey.ioに新しい絵文字 :murakamisan_tutinoko_crawling: (&#x60;murakamisan_tutinoko_crawling&#x60;)が追加されたかも。<br>$[x2 :murakamisan_tutinoko_crawling:]",
    "plain_content": "misskey.ioに新しい絵文字 :murakamisan_tutinoko_crawling: (`murakamisan_tutinoko_crawling`)が追加されたかも。\n$[x2 :murakamisan_tutinoko_crawling:]",
    "created_at": "2023-04-01T08:40:33.934Z",
    "emojis": [],
    "replies_count": 0,
    "reblogs_count": 71,
    "favourites_count": 0,
    "reblogged": false,
    "favourited": false,
    "muted": false,
    "sensitive": false,
    "spoiler_text": "",
    "visibility": "public",
    "media_attachments": [],
    "mentions": [],
    "tags": [],
    "card": null,
    "poll": null,
    "application": null,
    "language": null,
    "pinned": null,
    "emoji_reactions": [{
        "count": 2,
        "me": false,
        "name": "👍"
    }, 
    <redacted for simplicity>
    {
        "count": 1,
        "me": false,
        "name": ":murakamisan_tutinoko_yannnokastep_hara@.:"
    }],
    "bookmarked": false,
    "quote": false
}
```
</details>

### The Suggestions

1. Backward compatible way: consider adding an object field in the `Status` entity, named like `favorite`, to hold favorite's `id` and `created_at` fields.
2. Breaking change way: consider creating a new `Favorite` entity in `megalodon` to be used with `favorite` endpoints, instead of converting it to a `Status` entity.

Please let me know if I misunderstood any part of the library and how do you guys think about the suggestions. Thank you.

**Comment by mogita** [comment]
> Doesn't Misskey return the link header?

No I didn't find any pagination headers from their docs or the actual responses. Actually the "favorite ID" works if I fill it in the request parameters, i.e. `sinceId` or `untilId`. Can be tested [here](https://misskey-hub.net/docs/api/endpoints/i/favorites.html) (need to expand the "API Console" section).

For Mastodon (Pleroma not tested yet), I have implemented a parser for the `link` header. For Misskey, there seems to be no way around for now except that I implement an Axios request especially for it which is so not scalable... My product is lacking Misskey support in some components due to the difficulties working with their API design. Sigh.

**Comment by h3poteto** [comment]
refs: https://github.com/h3poteto/megalodon/issues/1669
