### ISSUE TITLE
Feature request: add ESM support

### ISSUE THREAD

**Issue by mashirozx** [h3poteto/megalodon#1701]
Currently we are using cjs modules, but it's not friendly to some modern tool chains, [see](https://arethetypeswrong.github.io/?p=megalodon%406.0.1).

This lib is currently compiled with `tsc`, but it can't compile into ESM perfectly, [see](https://github.com/microsoft/TypeScript/issues/18442). It may needs to introduce bundler like Rollup and SWC.

**Comment by ThatOneCalculator** [comment]
Related: #1923

**Comment by ThatOneCalculator** [comment]
Will be closed by #1963

**Comment by Ryuno-Ki** [comment]
Looks like that auto-close didn't happen :crying_cat_face:
