### ISSUE TITLE
wildebeest support

### ISSUE THREAD

**Issue by mirror-kt** [h3poteto/megalodon#1796]
[Wildebeest](https://github.com/cloudflare/wildebeest) is an ActivityPub and Mastodon-compatible server developed by Cloudflare.

Although not many features are implemented, it is worth supporting since it claims to be compatible with the Mastodon API.

Also, since Wildebeest itself does not have a writeable UI (a read-only UI is provided), a third-party app is required, and it would be great if fedistar could be used.

**Comment by mirror-kt** [comment]
From what I've read of megalodon's code, it seems to infer software from the `/.well-known/nodeinfo` response.
The nodeinfo generated by wildebeest does not contain the string "wildebeest" (e.x. https://wildebeest.mirror-kt.dev/.well-known/nodeinfo), so it seems to be unidentifiable.
We need to resolve this issue first.

**Comment by h3poteto** [comment]
The nodeinfo is here: https://wildebeest.mirror-kt.dev/nodeinfo/2.1
There is no problem, it has "wildebeest" string in it.
