### ISSUE TITLE
README is out-of-date and unnecessarily complicated

### ISSUE THREAD

**Issue by xarxziux** [h3poteto/megalodon#18]
As the title says, the README page needs to be updated.

Due to a recent(?) update to Mastodon, there is now a much simpler way of getting the access token directly through the web interface so the section "Authorization" seems obsolete.  I've been able to build a very minimalistic Node script just by adapting the section "Post Toot", skipping the earlier sections.

Your package is a lot easier to use than the README suggests.  You should update it to reflect that.

**Comment by h3poteto** [comment]
Is this what you are saying?
![screenshot from 2018-11-14 09-16-42](https://user-images.githubusercontent.com/4631959/48451494-04966d00-e7ee-11e8-8ff5-9239e1bc7158.png)

**Comment by xarxziux** [comment]
Yes.  Based on the important note [here](https://tinysubversions.com/notes/mastodon-bot/), I believe that functionality was added after the README was created.  I don't think the process in the README is necessary any more.

**Comment by h3poteto** [comment]
I don't think that `registerApp` and `fetchAccessToken` is unnecessary. Because `megalodon` is an API client library, so it is important to be able to register applications programmably.

And this library supports Pleroma. Can users get access token from web in Pleroma?

**Comment by xarxziux** [comment]
Fair enough.  I just thought it might make the library a little more accessible if you had a simpler README.  Maybe consider a quick-start guide that just has some code for posting a toot with the access token from the site.

I don't see a way of getting an access token from the Pleroma web interface.  :(

**Comment by alicerunsonfedora** [comment]
I noticed there was a lack of a function for it, but the base components are there. I implemented a new function to act like `registerApp` for Hyperspace: https://github.com/hyperspacedev/hyperspace/blob/master/src/utilities/login.tsx
