### ISSUE TITLE
Mastodon#getAccountFollowers `get_all` option does not work

### ISSUE THREAD

**Issue by skerit** [h3poteto/megalodon#1828]
I'm trying to get all my followers like so:

```js
let response = await client.getAccountFollowers(profile_id, {get_all: true});
```

But it always just returns 40 items, even though the response header does have a `link` value with `rel="next"` in it.

*edit*: I tested an older version of megalodon (v5.5.0) and there it works fine.

**Comment by h3poteto** [comment]
cc @fasiha

**Comment by fasiha** [comment]
Thanks for the tag @h3poteto!

@skerit tiny one-liner fix is in https://github.com/h3poteto/megalodon/pull/1830, hope this helps!
