### ISSUE TITLE
Megalodon's WebSocket reconnects already closed sockets

### ISSUE THREAD

**Issue by amyspark** [h3poteto/megalodon#20]
During debug of h3poteto/whalebird#553, I found out that if a websocket instance is stopped,
https://github.com/h3poteto/megalodon/blob/0a80a51542c081e4f187f0d100d2aefeead8557a/src/web_socket.ts#L61
if an error happens during the connection closure it is not only leaked to the caller, it also triggers a reconnection:
https://github.com/h3poteto/megalodon/blob/0a80a51542c081e4f187f0d100d2aefeead8557a/src/web_socket.ts#L130-L138

This means that the socket is left in a sort of 'zombie' state. It is still connected and emitting events; and if the caller removes the event handlers (like Whalebird does), the next error in the socket will trigger an `uncaughtException`.

**Comment by h3poteto** [comment]
I have an idea to fix it, so I will try.
