### ISSUE TITLE
Option to GET only public account statuses (GoToSocial)

### ISSUE THREAD

**Issue by Ryuno-Ki** [h3poteto/megalodon#2210]
Amazing project! I love it! My use case is to display my last public toot (not a reply or boost) on my homepage.

I'm almost there! Running my own GoToSocial instance at fedi.jaenis.ch I can study the API:
https://docs.gotosocial.org/en/latest/api/swagger/

I can see that there's an `only_public` flag that I cannot set in [Megalodon's implementation](https://github.com/h3poteto/megalodon/blob/fc366553dd9bec8c3769d06d5728736b84168b6e/megalodon/src/gotosocial.ts#L361-L372).

For now I'm overfetching and filtering the results (`status.visibility === "public"`) on the client. This incurs a little bit more data, which I would like to avoid (because it could mean visitors paying more than strictly necessary).

Is there a way to extend the API here? Or are there constraints (such as: same API for all fedi services)?

**Comment by Ryuno-Ki** [comment]
Are you accepting PRs on it? I could take an attempt then.

**Comment by h3poteto** [comment]
Of course, I'm waiting for your PRs. Thank you.

**Comment by Ryuno-Ki** [comment]
I've opened #2211 with the change.

Looking at the tests folder I could not see a folder or file for GoToSocial. Therefore no updates there.
I tested the changes by changing the files in the `node_modules` of an existing application and confirmed they're working (better than blindly accepting it, I feel).
