### ISSUE TITLE
Unable to send multipart/form-data (image) to /media endpoint

### ISSUE THREAD

**Issue by mrnocreativity** [h3poteto/megalodon#23]
I keep getting HTTP/400 feedback from the API when client.post()-ing to /api/v1/media.

I'm using FormData to create the formData object that get's submitted to the API.
Upon looking into the sourcecode (generated JS), I noticed that the content-type never gets set to multipart/formdata. 

You think this could be related?

**Comment by h3poteto** [comment]
Please show me your code?

The `post` method is wrapper of axios, so I think that you can use the same method of axios.
My code is here:
https://github.com/h3poteto/whalebird-desktop/blob/master/src/renderer/store/TimelineSpace/Modals/NewToot.js#L154-L171
