### ISSUE TITLE
Question about authentication

### ISSUE THREAD

**Issue by aschrijver** [h3poteto/megalodon#238]
I can’t figure out how registerApp with a random name ‘TestApp’ and url e.g. mastodon.social in any way relates to my personal account when getting clientId, clientSecret, authorizationCode. Is there another authentication flow where I provide username / password, before I can make this call? The app-related pages in Mastodon docs are missing. Any explanation appreciated: How does this work?

**Comment by h3poteto** [comment]
>  how registerApp with a random name ‘TestApp’ and url 

Please provide random name to `registerApp` arguments, for example:

```javascript
import Mastodon from 'megalodon'

Mastodon.registerApp('RandomAppName', {
  scopes: 'read write follow'
}, YOUR_URL)
```

As another way, you can register applications in your Mastodon page, like: https://mastodon.social/settings/applications
Please create new application, and you can get access token.

After that, please provide your access token:

```javascript
const client = new Mastodon(
  access_token,
  "https://mastodon.social"
)
```

**Comment by aschrijver** [comment]
Thanks for your help @h3poteto ! Yes, I get the way to retrieve an access token via the web GUI. That one speaks for itself. But it is the first method using `registerApp` that confuses me:

```js
// How does this relate in any way to my personal account if I 
//   do not authenticate with a username/pass prior to this call?
Mastodon.registerApp('RandomAppName', {
  scopes: 'read write follow'
}, 'https://mastodon.social')
```

**Comment by h3poteto** [comment]
If you want to create application which is authenticated by one account, e.g. bot applications, please use access token via the web GUI. It is no problem.

But if you want to create application which is authenticated by multiple accounts, e.g. Mastodon client for mobile application, please use `registerApp` method.

Recently I merged breaking changes, so authentication methods are changed too. So please refer: https://github.com/h3poteto/megalodon#authorization

**Comment by aschrijver** [comment]
Thanks a lot for your info, @h3poteto I will close this one now.
