### ISSUE TITLE
Drop Moment?

### ISSUE THREAD

**Issue by resynth1943** [h3poteto/megalodon#571]
Checking out some Mastodon libraries, and this one caught my eye. Looks good!

One question though: would you consider dropping Moment? Right now, this adds [200KB+ to the bundle...](https://bundlephobia.com/result?p=megalodon@3.3.2)

Use-case: would love to run this in a constrained environment (Web, Deno, etc.), and moment adds a lot of unnecessary bloat.

There's also [Luxon](https://bundlephobia.com/result?p=luxon@1.25.0), which adds 60KB.

A quick scan of the source shows that you're only using Moment in one place. In that case, I'd argue it isn't worth 200KB :-)

**Comment by h3poteto** [comment]
OK, I will consider it.
