### ISSUE TITLE
uploadMedia uses FormData internally that does not exist in node

### ISSUE THREAD

**Issue by wgroeneveld** [h3poteto/megalodon#714]
Hi there,

Been playing with this neat npm package, thanks! However, when I attempt to use `client.uploadMedia`, I can see in the source it uses "new FormData()" internally. FormData does not exist in node, except if I add `FormData = require('form-data');` to my js file. 

Note that I'm not using TypeScript, just plain vanilla JS. Without the additional added package, it crashes. Should be a dependency! 

Furthermore, after that's fixed, I consistently get a "400 Bad Request" at the /api/v1/media endpoint when trying to upload media on my Pleroma instance. Does this mean it's another bug or am I doing something else wrong?
`postStatus()` works well: the toot is visible. 

Thanks!

**Comment by h3poteto** [comment]
Hi.

I see. I will add a `form-data` in dependency: https://www.npmjs.com/package/form-data

**Comment by h3poteto** [comment]
> I consistently get a "400 Bad Request" at the /api/v1/media endpoint when trying to upload media on my Pleroma instance

I can upload a media to my Pleroma instance.

Please paste your code? And does Pleroma server say any errors when you call `client.uploadMedia` ?

**Comment by wgroeneveld** [comment]
I have tried numerous different things, and ultimately reverted to doing a POST request myself. Alas, even with the `got` package, I simply could not get multipart form data uploaded. In the end, I resorted to `axios`, and that works, using this:

```
	const formData = new FormData()
	formData.append('file', createReadStream(fileName))
	formData.append('description', description)

	const result = await axios.post(`${instance}/api/v1/media`, formData, {
      headers: {
        "Content-Type": `multipart/form-data; boundary=${formData.getBoundary()}`,
        "Authorization": `Bearer ${oauthToken}`
      }
    });

```

I hope that helps! If it works for you, I'd just close this issue, as getting form-data added as a dependency was more important for me ;-)

**Comment by h3poteto** [comment]
I can reproduce this issue. I will fix it.
```
(node:47258) UnhandledPromiseRejectionWarning: Error: Request failed with status code 400
    at createError (/home/h3poteto/src/github.com/h3poteto/megalodon/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/h3poteto/src/github.com/h3poteto/megalodon/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/h3poteto/src/github.com/h3poteto/megalodon/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:47258) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:47258) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by h3poteto** [comment]
Pleroma server says an error when I post it.
```
08:46:28.462 request_id=FnKbUQUq6Q1U7LQAJy_B [error] Internal server error: %Plug.Parsers.BadEncodingError{message: "invalid UTF-8 on urlencoded params, got byte 189", plug_status: 400}
```

**Comment by wgroeneveld** [comment]
Aha! Now we're getting somewhere! Great!

**Comment by h3poteto** [comment]
@wgroeneveld Hi, I fixed it. So please try v3.6.1.
